name: flutter_woocommerce

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:

  flutter:
    sdk: flutter

  # UI packages
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.1
  carousel_slider: ^4.2.1
  iconly: ^1.0.1
  shimmer: ^3.0.0
  ionicons: ^0.2.2
  # State Managment

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.2.1
  equatable: ^2.0.5
  get_it: ^7.2.0


  #Local DB
  shared_preferences: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Helper Methods
  dartz: ^0.10.1
  collection: 
  intl:
  timeago: 

  # WebView for the checkout
  webview_flutter: 

  # Convenient debugging
  logger: ^1.3.0
  
  # Render Html 
  flutter_html: ^2.2.1
  html_unescape: ^2.0.0

  # Http for connection
  http:



  # Others
  url_launcher: ^6.1.11
  share_plus: 
  cached_network_image: ^3.2.3

  

  
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  

  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: 
  
flutter_native_splash:
  image: assets/icon.png
  color: "ffffff"



  hive_generator:

  build_runner: 

  flutter_lints: ^2.0.0


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Light.ttf
        - asset: fonts/Urbanist-Regular.ttf
        - asset: fonts/Urbanist-Bold.ttf

    - family: Cairo
      fonts: 
        - asset: fonts/Cairo-Regular.ttf
